### ISSUE TITLE
[BUG]Error occurred during installation process: "Unexpected exit code: 1638."

### ISSUE THREAD

**Issue by HumanMus1c** [srilakshmikanthanp/clipbirdesk#8]
D:/Programs/ Clipbird/vc_redist.x64.exe /install /passive/ norestart wait.

![image](https://github.com/srilakshmikanthanp/clipbirdesk/assets/46023154/1955d5f4-4d7e-459b-a055-1b146ee16a68)

**Comment by srilakshmikanthanp** [comment]
Thank you for bringing up an issue. A lot has changed since v1.1.0, and I'm hopeful that the changes in [v1.2.0](https://github.com/srilakshmikanthanp/clipbirdesk/releases/tag/v1.2.0) address it. If you come across any problems, please inform me!

**Comment by srilakshmikanthanp** [comment]
I am closing this issue as completed, if you have any problem, please reopen it.
